version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/src-typescript/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/src-python/"
    schedule:
      interval: "daily"
