fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: double-quote-string-fixer

  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: isort
        stages:
          - commit
        args:
          - "--settings-file=tox.ini"
