name: "Generate Sphinx Docs"
on:
  - push
  - pull_request

jobs:
  generate-sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: Cerberus1746/sphinx-action@master
        with:
          build-command: |
            python -m sphinx -b html ${{ github.workspace }}/docs ${{ github.workspace }}/docs/build/

      - name: Commit documentation changes
        run: |
          git clone https://github.com/Cerberus1746/generic_lexer.git \
            --branch gh-pages \
            --single-branch gh-pages
          rm -r ${{ github.workspace }}/build/.doctrees
          cp -r ${{ github.workspace }}/build/ gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
