name: Tox Tests

on:
  - push
  - pull_request

jobs:
  tox-tests:
    runs-on: ${{matrix.platform}}
    name: Analyze

    strategy:
      max-parallel: 5
      matrix:
        platform:
        - ubuntu-latest
        #- macos-latest
        #- windows-latest
        
        python-version: 
        #- 2.7
        #- 3.6
        #- 3.7
        #- 3.8
        - 3.9

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@master
      with:
        python-version: ${{matrix.python-version}}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox
      run: tox
      env:
        PLATFORM: ${{matrix.platform}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
        COVERALLS_PARALLEL: true
  
  coveralls:
    name: Finish Coveralls
    needs: tox-tests
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
