name: "Tox Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-18.04

    strategy:
      max-parallel: 5
      matrix:
        python-version: 
        #- 2.7
        #- 3.6
        #- 3.7
        #- 3.8
        - 3.9

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    
    - name: Test with tox
      run: tox

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.2
